name: Push Mirror

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: "master"
          persist-credentials: false
          fetch-depth: 0

      - run: |
          date > generated.txt
          git push https://ipvb:${{ secrets.GITEE_PERSONAL_ACCESS_TOKENS }}@gitee.com/baulk/bucket.git master
